spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        #healthCheckPath: ${management.contextPath}/health
        healthCheckPath: /health
        healthCheckInterval: 5s
        instance-id: consul
        enabled: true
      enabled: true
  application:
    name: consul
server:
  port: 8082