server:
  port: 9001
  servlet:
      context-path: /generator
tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 10
    background-processor-delay: 30
    basedir: ${user.home}/tomcat/
spring:
    cloud:
    consul:
      discovery:
        service-name: generator
        register: true
        healthCheckPath: /actuator/health
        instanceId: ${spring.application.name}-${server.port}-${spring.cloud.client.hostname}
      host: localhost
      port: 8500
      config:
        enabled: true
        format: yaml
        data-key: generator
        prefix: config
        defaultContext: consul-config
    banner:
      charset: UTF-8
    http:
      encoding:
        force: true
        charset: UTF-8
    application:
        name: spring-boot-code-generator
        host: localhost
    freemarker:
        request-context-attribute: request
        suffix: .ftl
        content-type: text/html
        enabled: true
        cache: false
        charset: UTF-8
        allow-request-override: false
        expose-request-attributes: true
        expose-session-attributes: true
        expose-spring-macro-helpers: true
        #template-loader-path: classpath:/templates/
    mvc:
      static-path-pattern: /static/**